// web-traficandme-nuveau/src/components/incentives/incentives.tsx
'use client'

import { useTranslation } from 'react-i18next';

export default function Incentives() {
    const { t } = useTranslation();

    return (
        <div className="bg-white">
            <main className="isolate">
                <div className="bg-indigo-50">
                    <div className="mx-auto max-w-7xl py-24 sm:px-2 sm:py-32 lg:px-4">
                        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-10 px-4 lg:max-w-none lg:grid-cols-3">
                            {/* Real Time Updates */}
                            <div className="text-center sm:flex sm:text-left lg:block lg:text-center">
                                <div className="sm:shrink-0">
                                    <div className="flow-root">
                                        <img className="mx-auto h-24 w-28" src="https://tailwindui.com/plus-assets/img/ecommerce/icons/icon-delivery-light.svg" alt="" />
                                    </div>
                                </div>
                                <div className="mt-3 sm:mt-0 sm:ml-3 lg:mt-3 lg:ml-0">
                                    <h3 className="text-sm font-medium text-gray-900">{t('feature.real_time_updates.title')}</h3>
                                    <p className="mt-2 text-sm text-gray-500">{t('feature.real_time_updates.description')}</p>
                                </div>
                            </div>

                            {/* 24/7 Support */}
                            <div className="text-center sm:flex sm:text-left lg:block lg:text-center">
                                <div className="sm:shrink-0">
                                    <div className="flow-root">
                                        <img className="mx-auto h-24 w-28" src="https://tailwindui.com/plus-assets/img/ecommerce/icons/icon-chat-light.svg" alt="" />
                                    </div>
                                </div>
                                <div className="mt-3 sm:mt-0 sm:ml-3 lg:mt-3 lg:ml-0">
                                    <h3 className="text-sm font-medium text-gray-900">{t('feature.support_24_7.title')}</h3>
                                    <p className="mt-2 text-sm text-gray-500">{t('feature.support_24_7.description')}</p>
                                </div>
                            </div>

                            {/* Optimized Navigation */}
                            <div className="text-center sm:flex sm:text-left lg:block lg:text-center">
                                <div className="sm:shrink-0">
                                    <div className="flow-root">
                                        <img className="mx-auto h-24 w-28" src="https://tailwindui.com/plus-assets/img/ecommerce/icons/icon-fast-checkout-light.svg" alt="" />
                                    </div>
                                </div>
                                <div className="mt-3 sm:mt-0 sm:ml-3 lg:mt-3 lg:ml-0">
                                    <h3 className="text-sm font-medium text-gray-900">{t('feature.optimized_navigation.title')}</h3>
                                    <p className="mt-2 text-sm text-gray-500">{t('feature.optimized_navigation.description')}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}

// web-traficandme/src/app/components/incentives/incentives.component.ts
import { Component } from '@angular/core';
import {AccordionModule} from 'primeng/accordion';

@Component({
  selector: 'app-incentives',
  imports: [
    AccordionModule
  ],
  templateUrl: './incentives.component.html',
  standalone: true,
  styleUrl: './incentives.component.css'
})
export class IncentivesComponent {
}

<div class="bg-white">
  <main class="isolate">
    <div class="bg-indigo-50">
      <div class="mx-auto max-w-7xl py-24 sm:px-2 sm:py-32 lg:px-4">
        <div class="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-10 px-4 lg:max-w-none lg:grid-cols-3">
          <div class="text-center sm:flex sm:text-left lg:block lg:text-center">
            <div class="sm:shrink-0">
              <div class="flow-root">
                <img class="mx-auto h-24 w-28" src="https://tailwindui.com/plus-assets/img/ecommerce/icons/icon-delivery-light.svg" alt="">
              </div>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-3 lg:mt-3 lg:ml-0">
              <h3 class="text-sm font-medium text-gray-900">Mises à jour en temps réel</h3>
              <p class="mt-2 text-sm text-gray-500">Recevez des informations instantanées sur l'état du trafic, les accidents et les obstacles pour un trajet plus fluide.</p>
            </div>
          </div>
          <div class="text-center sm:flex sm:text-left lg:block lg:text-center">
            <div class="sm:shrink-0">
              <div class="flow-root">
                <img class="mx-auto h-24 w-28" src="https://tailwindui.com/plus-assets/img/ecommerce/icons/icon-chat-light.svg" alt="">
              </div>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-3 lg:mt-3 lg:ml-0">
              <h3 class="text-sm font-medium text-gray-900">Assistance 24/7</h3>
              <p class="mt-2 text-sm text-gray-500">Un support en continu pour vous aider à naviguer en toute sérénité, où que vous soyez.</p>
            </div>
          </div>
          <div class="text-center sm:flex sm:text-left lg:block lg:text-center">
            <div class="sm:shrink-0">
              <div class="flow-root">
                <img class="mx-auto h-24 w-28" src="https://tailwindui.com/plus-assets/img/ecommerce/icons/icon-fast-checkout-light.svg" alt="">
              </div>
            </div>
            <div class="mt-3 sm:mt-0 sm:ml-3 lg:mt-3 lg:ml-0">
              <h3 class="text-sm font-medium text-gray-900">Navigation optimisée</h3>
              <p class="mt-2 text-sm text-gray-500">Profitez d'un itinéraire rapide et sécurisé grâce à nos algorithmes avancés de guidage.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
