// web-traficandme-nuveau/src/components/content-section/content-section.tsx
'use client'

import { useTranslation } from 'react-i18next';

export default function ContentSection() {
    const { t } = useTranslation();

    return (
        <div className="mx-auto mt-32 max-w-7xl px-6 sm:mt-40 lg:px-8">


            <div className="mx-auto max-w-2xl lg:mx-0">
                <h2 className="text-4xl font-semibold tracking-tight text-pretty text-gray-900 sm:text-5xl">
                    {t('content-section.values_title')}
                </h2>
                <p className="mt-6 text-lg/8 text-gray-600">
                    {t('content-section.description')}
                </p>
            </div>


            <dl className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 text-base/7 sm:grid-cols-2 lg:mx-0 lg:max-w-none lg:grid-cols-3">
                <div>
                    <dt className="font-semibold text-gray-900">{t('content-section.be_world_class')}</dt>
                    <dd className="mt-1 text-gray-600">{t('content-section.be_world_class_desc')}</dd>
                </div>
                <div>
                    <dt className="font-semibold text-gray-900">{t('content-section.share_knowlege')}</dt>
                    <dd className="mt-1 text-gray-600">{t('content-section.share_knowlege_desc')}</dd>
                </div>
                <div>
                    <dt className="font-semibold text-gray-900">{t('content-section.always_learning')}</dt>
                    <dd className="mt-1 text-gray-600">{t('content-section.always_learning_desc')}</dd>
                </div>

            </dl>
            <div className="mt-32 sm:mt-40 xl:mx-auto xl:max-w-7xl xl:px-8">
                <img
                    alt={t('about.bannerAlt')}
                    src="images/home/holidays.jpg"
                    className="aspect-5/2 w-full object-cover xl:rounded-3xl"
                />
            </div>
        </div>
    );
}

// web-traficandme/src/app/components/content-section/content-section.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-content-section',
  imports: [],
  templateUrl: './content-section.component.html',
  standalone: true,
  styleUrl: './content-section.component.css'
})
export class ContentSectionComponent {

}

<div class="mt-32 overflow-hidden sm:mt-40">
  <div class="mx-auto max-w-7xl px-6 lg:flex lg:px-8">
    <div class="mx-auto grid max-w-2xl grid-cols-1 gap-x-12 gap-y-16 lg:mx-0 lg:max-w-none lg:min-w-full lg:flex-none lg:gap-y-8">
      <div class="lg:col-end-1 lg:w-full lg:max-w-lg lg:pb-8">
        <h2 class="text-4xl font-semibold tracking-tight text-gray-900 sm:text-5xl">Une navigation intelligente</h2>
        <p class="mt-6 text-xl/8 text-gray-600">Notre application vous informe en temps réel sur les conditions de circulation, les accidents et les routes fermées pour un trajet sans stress.</p>
        <p class="mt-6 text-base/7 text-gray-600">Évitez les embouteillages et trouvez l'itinéraire le plus rapide grâce à notre technologie avancée de navigation.</p>
      </div>
      <div class="flex flex-wrap items-start justify-end gap-6 sm:gap-8 lg:contents">
        <div class="w-0 flex-auto lg:ml-auto lg:w-auto lg:flex-none lg:self-end">
          <img src="assets/images/home/holidays.jpg" alt="" class="aspect-7/5 w-[37rem] max-w-none rounded-2xl bg-gray-50 object-cover">
        </div>
        <div class="contents lg:col-span-2 lg:col-end-2 lg:ml-auto lg:flex lg:w-[37rem] lg:items-start lg:justify-end lg:gap-x-8">
          <div class="order-first flex w-64 flex-none justify-end self-end lg:w-auto">
            <img src="assets/images/home/flat.jpg" alt="" class="aspect-4/3 w-[24rem] max-w-none flex-none rounded-2xl bg-gray-50 object-cover">
          </div>
          <div class="flex w-96 flex-auto justify-end lg:w-auto lg:flex-none">
            <img src="assets/images/home/navigation.jpg" alt="" class="aspect-7/5 w-[37rem] max-w-none flex-none rounded-2xl bg-gray-50 object-cover">
          </div>
          <div class="hidden sm:block sm:w-0 sm:flex-auto lg:w-auto lg:flex-none">
            <img src="assets/images/home/application.jpg" alt="" class="aspect-4/3 w-[24rem] max-w-none rounded-2xl bg-gray-50 object-cover">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
