// web-traficandme/src/app/components/header/header.component.ts
import {Component, Inject} from '@angular/core';
import {RouterLink} from '@angular/router';
import {LoginComponent} from '../../connection/login/login.component';
import {CountrySelectorComponent} from '../country-selector/country-selector.component';
import {TranslateModule} from '@ngx-translate/core';
import {ToastService} from '../toast/toast.service';
import {MessageService} from 'primeng/api';

@Component({
  selector: 'app-header',
  imports: [RouterLink, LoginComponent, CountrySelectorComponent, TranslateModule],
  templateUrl: './header.component.html',
  standalone: true,
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  constructor(private toastService: ToastService,private messageService: MessageService) {}
  visible: boolean = false;

  showDialog(event : boolean) {
    this.visible = event;
  }

  notAvailable() {
    this.toastService.showWarn("L'action n'est 'pas disponible pour le moment",this.messageService);
  }
}

<header class="bg-white">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-4 lg:px-8" aria-label="Global">
    <div class="flex flex-1">
      <div class="hidden lg:flex lg:gap-x-12">
        <a routerLink="" href="#" class="text-sm/6 font-semibold text-gray-900"><i class="pi pi-home mr-1"></i>{{ 'header.home' | translate }}</a>
        <a style="display: flex;align-items: center" routerLink="map" href="#" class="text-sm/6 font-semibold text-gray-900"><i class="pi pi-map mr-1"></i>{{ 'header.map' | translate }}</a>
        <a routerLink="" type="button" (click)="notAvailable()" class="text-sm/6 font-semibold text-gray-900"><i class="pi pi-building mr-1"></i>{{ 'header.company' | translate }}</a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
    </div>
    <a href="#" class="-m-1.5 ">
      <span class="sr-only">{{ 'header.company' | translate }}</span>
      <img class="h-12 w-auto" [src]="'assets/images/logo/logo_2.png'" alt="Logo" height="800" width="800">
    </a>
    <div class="flex flex-1 justify-end">
      <button  type="button" (click)="showDialog(true)"  class="cursor-pointer text-sm/6 font-semibold text-gray-900 ">{{ 'header.log-in' | translate }}<span aria-hidden="true">&rarr;</span></button>
      <app-country-selector/>
    </div>
  </nav>
  <!-- Mobile menu, show/hide based on menu open state. TODO partie mobile  -->
  <div class="lg:hidden" role="dialog" aria-modal="true">
    <!-- Background backdrop, show/hide based on slide-over state. -->
    <div class="fixed inset-0 z-10"></div>
    <div class="fixed inset-y-0 left-0 z-10 w-full overflow-y-auto bg-white px-6 py-6">
      <div class="flex items-center justify-between">
        <div class="flex flex-1">
          <button type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Close menu</span>
            <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="">
        </a>
        <div class="flex flex-1 justify-end">
          <button (click)="showDialog(true)"  class="text-sm/6 font-semibold text-gray-900">Log in <span aria-hidden="true">&rarr;</span></button>
        </div>
      </div>
      <div class="mt-6 space-y-2">
        <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50">Product</a>
        <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50">Features</a>
        <a href="#" class="-mx-3 block rounded-lg px-3 py-2 text-base/7 font-semibold text-gray-900 hover:bg-gray-50">Company</a>
      </div>
    </div>
  </div>
</header>
<app-login [(visible)]="visible" (visibleChange)="showDialog($event)" />

// web-traficandme-nuveau/src/components/header/header.tsx
import { useState } from 'react';
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
import Languages from "../languages/languages.tsx";
import {Dialog} from "../../assets/kit-ui/dialog.tsx";
import Login from "../../connexion/login/login.tsx";
import Register from "../../connexion/register/register.tsx";
import {Menu, MenuButton, MenuItem, MenuItems} from "@headlessui/react";
import {Link} from "react-router-dom";
import {useTranslation} from "react-i18next";

export interface interfaceLanguages {
    name: string
    img : string
}

const navigation = [
    { name: 'Product', href: '#' },
    { name: 'Features', href: '#' },
    { name: 'Company', href: '#' },
];


const languages : interfaceLanguages[] = [
    { name: 'en', img: 'images/languages/english.png' },
    { name: 'fr', img: 'images/languages/french.png' },
];

export default function Header() {
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const [isOpenLogin, setIsOpenLogin] = useState(false);
    const [isOpenRegister, setIsOpenRegister] = useState(false);
    const { t } = useTranslation();
    const user : boolean = false;

    const toggleMobileMenu = () => {
        setMobileMenuOpen(!mobileMenuOpen);
    };


    function handleLogout() {

    }

    return (
        <header className="bg-white">
            <nav className="mx-auto flex max-w-7xl items-center justify-between p-4 lg:px-8" aria-label="Global">
                <div className="flex flex-1">
                    <div className="hidden lg:flex lg:gap-x-12">
                        <Link to="/" className="text-sm font-semibold text-gray-900">
                            <i className="pi pi-home mr-1"></i>{t("header.home")}
                        </Link>
                        <Link to="map" className="text-sm font-semibold text-gray-900 flex items-center">
                            <i className="pi pi-map mr-1"></i>{t("header.map")}
                        </Link>
                        <Link
                            to="/about"
                            className="cursor-pointer text-sm font-semibold text-gray-900"
                            onClick={() => alert('This section is not available')}
                        >
                            <i className="pi pi-building mr-1"></i> {t("header.about")}
                        </Link>
                    </div>
                    <div className="flex lg:hidden">
                        <button
                            type="button"
                            onClick={toggleMobileMenu}
                            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                        >
                            <span className="sr-only">Open main menu</span>
                            <Bars3Icon className="size-6" />
                        </button>
                    </div>
                </div>

                <a href="#" className="-m-1.5">
                    <span className="sr-only">Company</span>
                    <img
                        className="h-12 w-auto"
                        src="/images/logo/logo_2.png"
                        alt="Logo"
                        height="800"
                        width="800"
                    />
                </a>

                <div className="flex flex-1 justify-end">
                    {user ? (
                        <Menu as="div" className="relative ml-3">
                            <div>
                                <MenuButton
                                    className="relative flex rounded-full bg-gray-800 text-sm focus:ring-offset-2 focus:ring-offset-gray-800">
                                    <span className="absolute -inset-1.5"/>
                                    <img alt="Profile" src="/image/user1.png" className="h-8 w-8 rounded-full"/>
                                </MenuButton>
                            </div>
                            <MenuItems
                                className="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5">
                                <MenuItem>
                                    {({active}) => (
                                        <Link to="/profile" className={`block px-4 py-2 text-sm ${active ? 'bg-gray-100' : ''}`}>
                                            {t("profile.title")}
                                        </Link>
                                    )}
                                </MenuItem>
                                <MenuItem>
                                    {({active}) => (
                                        <button onClick={handleLogout}
                                                className={`block w-full text-left px-4 py-2 text-sm ${active ? 'bg-gray-100' : ''}`}>
                                            {t("logout")}
                                        </button>
                                    )}
                                </MenuItem>
                            </MenuItems>
                        </Menu>
                    ) : (
                        <div className="hidden lg:flex lg:flex-1 lg:justify-end">
                            <button className="cursor-pointer text-sm font-semibold text-gray-900" onClick={() => setIsOpenRegister(true)}>
                                {t("header.register")}
                            </button>
                            <button className="cursor-pointer ml-5 text-sm font-semibold text-gray-900" onClick={() => setIsOpenLogin(true)}>
                                {t("header.login")} <span aria-hidden="true">&rarr;</span>
                            </button>
                        </div>
                    )}
                    <Languages languages={languages} />

                </div>
            </nav>

            {/* Mobile menu */}
            {mobileMenuOpen && (
                <div className="lg:hidden fixed inset-0 z-10">
                    <div className="fixed inset-0 z-10 bg-black/50" onClick={toggleMobileMenu}></div>
                    <div className="fixed inset-y-0 left-0 z-10 w-full overflow-y-auto bg-white px-6 py-6">
                        <div className="flex items-center justify-between">
                            <div className="flex flex-1">
                                <button
                                    type="button"
                                    onClick={toggleMobileMenu}
                                    className="-m-2.5 rounded-md p-2.5 text-gray-700"
                                >
                                    <span className="sr-only">Close menu</span>
                                    <XMarkIcon className="size-6" />
                                </button>
                            </div>
                            <a href="#" className="-m-1.5 p-1.5">
                                <span className="sr-only">Company</span>
                                <img className="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="Logo" />
                            </a>
                        </div>
                        <div className="mt-6 space-y-2">
                            {navigation.map((item) => (
                                <a
                                    key={item.name}
                                    href={item.href}
                                    className="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold text-gray-900 hover:bg-gray-50"
                                >
                                    {item.name}
                                </a>
                            ))}
                        </div>
                    </div>
                </div>
            )}
            <Dialog style={{zIndex: 11, position: "fixed", top: 0, left: 0, right: 0, bottom: 0, display: "flex", justifyContent: "center", alignItems: "center"}} open={isOpenLogin} onClose={() => setIsOpenLogin(false)}>
                <Login closeModal={() => setIsOpenLogin(false)} />
            </Dialog>
            <Dialog  style={{zIndex: 11, position: "fixed", top: 0, left: 0, right: 0, bottom: 0, display: "flex", justifyContent: "center", alignItems: "center"}} open={isOpenRegister} onClose={() => setIsOpenRegister(false)}>
                <Register closeModal={() => setIsOpenRegister(false)} />
            </Dialog>
        </header>
    );
}
